### ISSUE TITLE
Win percentage is not calculated on champ removal

### ISSUE THREAD

**Issue by jordantas** [greelz/teamcomps#6] opened 2019-11-17 06:54 UTC

**Comment by greelz** [comment] 2019-11-24 21:43
Fixed in two ways:
1) We now have an "X" button to remove champions more easily. We'll recalculate if you click that (which I still don't know if that's the right choice, but whatever). 
2) If a user is manually erasing a champion, we are (by design) not recalculating. It's weird to decide at which time to recalculate. Maybe at the end, but likely the user will retype another search. 
3) We now also show the list of champions that are relevant to the query above the win percentage.

**Closed by greelz** 2019-11-24 21:43 UTC
